package:
  name: spiceql
  version: 0.0.1 # {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/USGS-Astrogeology/SpiceQL.git
build:
  string: {{ environ.get("GIT_DESCRIBE_HASH", "dev") }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake >=3.14
    - pip
    - swig
    - fmt <8
  run:
    - cpp-filesystem
    - python>=3
    - cspice-cmake
  host:
    - cpp-filesystem
    - python >=3
    - cspice-cmake

test:
  imports:
    - pyspiceql
  commands:
    - test -e $PREFIX/lib/libSpiceQL${SHLIB_EXT}  # [unix]
    - test -e $PREFIX/include/SpideQL/sugar_spice.h  # [unix]
    - if not exist %LIBRARY_BIN%\SpiceQL.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\SpiceQL.lib exit 1  # [win]

about:
  home: https://sugar-spice.readthedocs.io/en/latest/#docs
  license: None
summary: "This Library provides a C++ interface querying, reading and writing Naif SPICE kernels."

